{{- if eq .Values.managementUi.enabled true }}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vauthenticator-management-ui.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.managementUi.ingress.class }}
    {{- with .Values.managementUi.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vauthenticator-management-ui.name" . }}
                port:
                  number: {{ .Values.managementUi.server.port }}
      host: {{  .Values.managementUi.ingress.host }}
    {{- with .Values.managementUi.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vauthenticator-management-ui-assets.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.applicationAssets.ingress.class }}
    {{- with .Values.managementUiAssets.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vauthenticator-management-ui-assets.name" . }}
                port:
                  number: {{ .Values.applicationAssets.server.port }}
      host: {{  .Values.managementUiAssets.ingress.host }}
    {{- with .Values.managementUiAssets.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}

  {{ end }}