{{- if eq .Values.managementUi.enabled true }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vauthenticator-management-ui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vauthenticator-management-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.managementUi.service.type }}
  ports:
    - port: {{ .Values.managementUi.server.port }}
      name: http
  selector:
    {{- include "vauthenticator-management-ui.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vauthenticator-management-ui-assets.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vauthenticator-management-ui-assets.labels" . | nindent 4 }}
spec:
  type: {{ .Values.applicationAssets.service.type }}
  ports:
    - port: 80
      name: http
  selector:
    {{- include "vauthenticator-management-ui-assets.selectorLabels" . | nindent 4 }}

  {{ end }}