{{- if eq .Values.aws.eks.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vauthenticator.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.eks.serviceAccount.iamRole.arn }}
  {{ end }}