{{- if eq .Values.managementUiAssets.enabled true }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vauthenticator-management-ui-assets.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.managementUiAssets.replicaCount }}
  selector:
    matchLabels:
  {{- include "vauthenticator-management-ui-assets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.managementUiAssets.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.managementUiAssets.lables }}
      {{- toYaml .Values.managementUiAssets.lables | nindent 8 }}
      {{ end }}
    {{- include "vauthenticator-management-ui-assets.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.aws.eks.serviceAccount.enabled true }}
      serviceAccountName: {{ include "vauthenticator-management-ui-assets.name" . }}
        {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.managementUiAssets.image.repository }}:{{ .Values.managementUiAssets.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.managementUiAssets.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /asset/healthz_bundle.js
              port: 80
            initialDelaySeconds: {{ .Values.managementUiAssets.pod.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.managementUiAssets.pod.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /asset/healthz_bundle.js
              port: 80
            initialDelaySeconds: {{ .Values.managementUiAssets.pod.probes.rediness.initialDelaySeconds }}
            periodSeconds: {{ .Values.managementUiAssets.pod.probes.rediness.periodSeconds }}
          resources:
          {{- toYaml .Values.managementUiAssets.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "vauthenticator-management-ui-assets.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vauthenticator-management-ui-assets.labels" . | nindent 4 }}
spec:
  type: {{ .Values.applicationAssets.service.type }}
  ports:
    - port: 80
      name: http
  selector:
    {{- include "vauthenticator-management-ui-assets.selectorLabels" . | nindent 4 }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vauthenticator-management-ui-assets.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.applicationAssets.ingress.class }}
    {{- with .Values.managementUiAssets.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vauthenticator-management-ui-assets.name" . }}
                port:
                  number: {{ .Values.applicationAssets.server.port }}
      host: {{  .Values.managementUiAssets.ingress.host }}
    {{- with .Values.managementUiAssets.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}

  {{ end }}